language: python
python:
  - "2.7"

install:
  # Install Sublime Text 2
  - sudo add-apt-repository ppa:webupd8team/sublime-text-2 -y
  - sudo apt-get update
  - sudo apt-get install sublime-text -y
  - sudo ln -s /usr/bin/subl /usr/bin/sublime_text

  # List Sublime Text info for debugging
  - sublime_text --version

  # Install dev dependencies
  - pip install -r requirements-dev.txt

  # Install our plugin
  - mkdir -p ~/.config/sublime-text-2/Packages/
  - ./symlink.sh

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Run our tests
  - SUBLIME_TESTS_AUTO_KILL=TRUE ./test.sh

notifications:
  email: false
